### SEO, Analytics & 3rd-party
netlify_forms = false # add data-netlify attribute to contact and newsletter forms, false to disable Netlify forms
# gtm_id = '' # GTM tracking (leave blank to use GA)
disallow_search_engines = false # Disallow search engine crawling in robots.txt

### Content
favicon = true # Enable favicon, add your favicon files to /static/ directory
avatar = 'avatar.jpg' # Custom avatar image in /assets/
grayscale_avatar = false # Add a grayscale filter to the avatar image
author = 'AJ FIte' # Default author for <head> meta
description = "Home page for software engineer AJ Fite" # Add a global meta description to <head>
footer_text = "" # Customize footer text
fallback_text = "No content available yet. Coming soon." # Fallback text for empty content
label_drafts = true # Add a label indicator next to the title of any built drafts (dev only)

# Customize newsletter text
newsletter_header = "This is my custom newsletter header with a captivating title."
newsletter_description = "This is my custom newsletter description that tells you why you should sign up."
newsletter_submit = "Join now"
global_newsletter = false # Enable newsletter site-wide

# CSS / JavaScript
enable_postcss = false # Enable if you're using npm and want to utilize PostCSS processing
#custom_css = 'custom.css' # Add the specified file to assets before setting this param to avoid errors
#custom_js = 'custom.js' # Add the specified file to assets before setting this param to avoid errors

### Web schemas
# Open Graph
images = ['images/default.jpg'] # Fallback for Open Graph and Twitter Cards images if none are present in front matter. Enter path to the image.
ogLocale = "en_US" # Open graph locale

# Twitter Cards
twitterSite = "ajfite" # Enter your twitter handle without the @
twitterCreator = "ajfite" # Enter your twitter handle without the @

# JSON-LD structured data schemas
schemaName = "AJ Fite" # Enter your name
schemaLocale = "en-US" # Structured data locale
schemaImage = "images/default.png" # Image for Person structured data schema. Enter path to the image.
schemaImageWidth = 453 # Width of the above image
schemaImageHeight = 455 # Height of the above image

### Social
# Show social links in footer, home hero section, or about page
footer_socials = true
home_hero_socials = true
about_page_socials = true

# Enable or disable individual social icons
[social.links]
  #twitter = "ajfite"
  github = "ajfite"
  #stack_overflow = "userid/username" # include user id
  email = "me@ajfite.com"
  linkedin = "ajfite" # Comment out to disable
  mastodon_server = "mastodon.social" # include subdomains if relevant, scheme not needed (defaults to https)
  mastodon_user = "ajfite" # don't include preceding @
  bluesky_user = "ajfite.com"


# Enable or disable individual social share icons in posts
[social.share]
  bluesky = true
  facebook = true
  linkedin = true
  twitter = false
  reddit = true
  email = true