stages:
  - build and deploy

variables:
  GIT_SUBMODULE_STRATEGY: recursive

beta:
  stage: build and deploy
  
  script:
    - hostname -A
    - pwd
    - hugo version
    - hugo --gc --minify --noTimes --noChmod --cleanDestinationDir -b "https://beta.ajfite.com/" -d /www/ajfite.com/beta/

  tags:
    - webserver

prod:
  stage: build and deploy

  script:
    - hugo --gc --minify --noTimes --noChmod --cleanDestinationDir -d /www/ajfite.com/www/

  rules:
    - if: $CI_COMMIT_BRANCH == "master"
      when: manual

  tags:
    - webserver