stages:
  - build and deploy
    
build:
  stage: build
  
  script:
    - BUNDLE_GEMFILE=Gemfile bundle install --deployment --clean
    - bundle exec jekyll build -d /www/ajfite.com/www/

  tags:
    - fremont
