# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: AJ Fite
email: me@ajfite.com
description: > # this means to ignore newlines until "baseurl:"
  The personal website for A.J. Fite, a senior Computer Engineering major
  at Cal Poly San Luis Obispo.  Personal projects, random ramblings, and
  other content of interest can be found here.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ajfite.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: ajfite
github_username:  goldman60

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-bootstrap-sass

collections:
  posts:
    output: true
    permalink: /blog/:year/:month/:day/:title.html

defaults:
  - scope:
      path: "assets/images"
    values:
      image: true

bootstrap:
  assets: true

google_analytics: UA-50434529-1
  
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
